parser: fix f referenced before assignment
These changes fix the following error, which occurs because the
variable "f" can be used without being properly assigned or initialized first:
File "Post/parser.py", line 98, in parse
    num_similar_errors = f.get_similar_fails_count()
UnboundLocalError: local variable 'f' referenced before assignment

Signed-off-by: Thomas Perrot <thomas.perrot@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>